### ISSUE TITLE
Unsupported --parallel flag issued

### ISSUE THREAD

**Issue by JorritSalverda** [rust-lang/cmake-rs#143] opened 2022-02-18 22:02 UTC
I'm trying to build a Lambda function in Rust to write to Kafka using the `rdkafka` crate as follows:

```toml
[dependencies]
rdkafka = { version = "0.28.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static", "cmake-build"] }
```

I'm building it using Docker image `ekidd/rust-musl-builder:1.57.0` with apt-get package `libsasl2-dev` installed before running `cargo build --release --target x86_64-unknown-linux-musl`.

Unfortunately when this crate gets build it adds a `--parallel` flag that's not supported by the `cmake` version in that Docker image. Is there any way to disable this flag or autodetect that it's not supported?

See https://github.com/emk/rust-musl-builder/issues/138 for the issue with more detail on the error.

**Comment by aloucks** [comment] 2022-02-20 16:45
A bugfix for `MSBuild` refactored the way `NUM_JOBS` was a applied and used the new(er) `--parallel` flag in `cmake`. 

It looks like the minimum supported version of `cmake` is now `3.12` (where as `Ubuntu 18.04 LTS` is on `3.10`). That version of Ubuntu is only supported for another year. Perhaps another path forward would be to update `rust-musl-builder` to use `Ubuntu 20.04 LTS` which appears to use `cmake` `3.16`.

See also: [#123](https://github.com/alexcrichton/cmake-rs/pull/123#issuecomment-889360937)

**Comment by fpagliughi** [comment] 2022-02-23 22:11
Note that this is a duplicate of issue #131

**Closed** 2022-05-12 09:43 UTC
